import os
import json
from typing import List, Dict, Any, Optional
import fnmatch
from .core.config import Config
from .core.models import PRDetails
from .services.github_service import GitHubService
from .services.ai_service import AIService
from .utils.diff_parser import DiffParser
from .utils.code_analyzer import CodeAnalyzer

class PRReviewApplication:
  def __init__(self) -> None:
    """Initialize the PR Review Application with required services."""
    self._setup_services()

  def _setup_services(self) -> None:
    """Set up all required services."""
    gh_client = Config.initialize_clients()
    self.github_service = GitHubService(gh_client)
    self.ai_service = AIService()
    self.code_analyzer = CodeAnalyzer(self.ai_service)
    self.diff_parser = DiffParser()

  def run(self) -> None:
    """Execute the main PR review process."""
    try:
      if not self._is_valid_event():
        print("Exiting due to invalid or unsupported event.")
        return

      pr_details = self._process_pr()
      if not pr_details:
        print("Failed to process PR details or no diff found to analyze.")
        return
      
      print("PR Review process completed.")

    except Exception as error:
      print(f"Error in run: {error}")
      import traceback
      traceback.print_exc()

  def _is_valid_event(self) -> bool:
    """Check if the GitHub event is supported."""
    event_name = os.environ.get("GITHUB_EVENT_NAME")
    if event_name == "pull_request":
        print(f"Processing event: {event_name}")
        return True

    print(f"Unsupported event: {event_name}. Expected 'pull_request'.")
    return False

  def _process_pr(self) -> Optional[PRDetails]:
    """Process the PR and create review comments if needed. Returns PRDetails or None."""
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        print("Error: GITHUB_EVENT_PATH environment variable not set.")
        return None
    if not os.path.exists(event_path):
        print(f"Error: GITHUB_EVENT_PATH file not found at {event_path}")
        return None

    try:
        pr_details = self.github_service.get_pr_details(event_path)
    except Exception as e:
        print(f"Error getting PR details: {e}")
        import traceback
        traceback.print_exc()
        return None

    diff = self.github_service.get_diff(pr_details.owner, pr_details.repo, pr_details.pull_number)
    
    if not diff:
      print("No diff found or failed to fetch diff for PR.")
      return pr_details 

    parsed_diff = self.diff_parser.parse_diff(diff)
    if not parsed_diff:
        print("Diff was present but parsing resulted in no actionable changes.")
        return pr_details 

    filtered_diff = self._filter_diff(parsed_diff)
    if not filtered_diff:
        print("All diff content was filtered out by exclude patterns.")
        return pr_details

    comments = self.code_analyzer.analyze_code(filtered_diff, pr_details)
    
    if comments:
      self.github_service.create_review_comment(pr_details, comments)
      print(f"Successfully created {len(comments)} review comments.")
    else:
      print("No review comments generated by AI for this diff.")
    return pr_details

  def _filter_diff(self, parsed_diff: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Filter diff based on exclude patterns from environment variables."""
    exclude_patterns = self._get_exclude_patterns()
    return [
      file for file in parsed_diff
      if not any(fnmatch.fnmatch(file.get('path', ''), pattern) 
            for pattern in exclude_patterns)
    ]

  def _get_exclude_patterns(self) -> List[str]:
    """Get and process exclude patterns from environment variables."""
    return [s.strip() for s in os.environ.get("INPUT_EXCLUDE", "").split(",")]

if __name__ == "__main__":
  app = PRReviewApplication()
  app.run()
